name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate
        run: ./gradlew run
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: output
